- hosts: all
  tasks:
  - name: Copy the quest agent users.allow for backup
    copy:
      src: /etc/opt/quest/vas/users.allow
      dest: /etc/opt/quest/vas/users.allow.backup
      remote_src: yes

  - name: Copy sudoers file for backup
    copy:
      src: /etc/sudoers
      dest: /etc/sudoers.backup
      remote_src: yes

  - name: Append users.allow with svc_1900
    lineinfile:
      path: /etc/opt/quest/vas/users.allow
      line: svc_1900

  - name: Update /etc/sudoers file with commands for svc_1900
    blockinfile:
      path: /etc/sudoers
      insertbefore: "## Allows members of the 'sys' group to run networking, software,"
      block: |
        svc_1900        ALL=(ALL)       NOPASSWD: /usr/sbin/lsof
        svc_1900        ALL=(ALL)       NOPASSWD: /bin/ethtool
        svc_1900        ALL=(ALL)       NOPASSWD: /usr/bin/netstat
        svc_1900        ALL=(ALL)       NOPASSWD: /usr/sbin/dmidecode
      validate: 'visudo -cf %s'